[package]
name = "audio_backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dsp-core"
path = "src/bin/dsp-core.rs"

[dependencies]
dsp = { workspace = true }
engine = { workspace = true }
cpal = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
ringbuf = { workspace = true }
rosc = { workspace = true }
tokio = { workspace = true }
sequencer = { workspace = true }
hound = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
os_dls = { workspace = true }
