[package]
name = "audio_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = {workspace = true}
anyhow = {workspace = true}
log = {workspace = true}
env_logger = {workspace = true}
crossbeam = {workspace = true}
sequencer = {workspace = true}