[package]
name = "sequencer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow ={ workspace = true }
bincode = {workspace = true}
clap = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
