[workspace]
resolver = "2"
members = ["audio_backend", "harmony", "sequencer"]
default-members = ["sequencer"]
exclude = ["frontend/src-tauri"]

[workspace.dependencies]
cpal = "0.15"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
crossbeam = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"